-- ============================================================================
-- Migration: 0008_publication_planner.sql
-- Description: Adaptive Publication Planner & Temporal Sequencing Engine (PUBLICATION-1)
-- Semantics:
--   1. Strict separation of states:
--      - articles.status: 'draft' | 'published' | 'scheduled' (article lifecycle)
--      - article_publication_readiness.overall_status: 'READY_TO_SCHEDULE' etc. (gate snapshot)
--      - article_publication_plans.plan_status: 'PLANNED' | 'SUPERSEDED' | 'CANCELLED' | 'BLOCKED' (planning lifecycle)
--   2. Invariant: Only 'READY_TO_SCHEDULE' articles with matching content_hash and featured_asset_id may have an active plan.
--   3. Partial Unique Index: Exactly ONE active plan ('PLANNED') per article at any time.
--   4. Operational Timezone: Standardized on 'Asia/Jakarta' (WIB, UTC+7).
-- Safety: Additive only. Preserves all existing tables, columns, indexes, and data.
-- ============================================================================

-- 1. Table: article_publication_plans
-- Stores deterministic publication window assignments generated by PUBLICATION-1
CREATE TABLE IF NOT EXISTS article_publication_plans (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    plan_id TEXT NOT NULL UNIQUE,                       -- E.g. 'plan_k8f92j4n8d'
    article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    readiness_id INTEGER NOT NULL REFERENCES article_publication_readiness(id),
    
    -- Cryptographic Invariants
    content_hash TEXT NOT NULL,                         -- Must match articles.content_hash
    featured_asset_id TEXT NOT NULL,                    -- Must match active featured media
    
    -- Publication Window Assignment
    target_publish_at DATETIME NOT NULL,                -- UTC ISO 8601
    target_publish_local TEXT NOT NULL,                 -- 'YYYY-MM-DD HH:MM:SS WIB'
    timezone TEXT NOT NULL DEFAULT 'Asia/Jakarta',
    
    -- Plan Classification & Provenance
    plan_status TEXT NOT NULL DEFAULT 'PLANNED',        -- PLANNED | SUPERSEDED | CANCELLED | BLOCKED
    planner_profile TEXT NOT NULL,                      -- 'NEW' | 'GROWING' | 'ESTABLISHED' | 'HIGH_AUTHORITY'
    planner_version TEXT NOT NULL DEFAULT '1.0.0',
    priority_score REAL NOT NULL,                       -- Computed sorting score
    slot_index INTEGER NOT NULL,                        -- Ordinal slot for the target day (1, 2, ...)
    jitter_seconds INTEGER NOT NULL DEFAULT 0,
    
    -- Audit & Traceability
    reason_codes TEXT NOT NULL,                         -- JSON Array: ['FIFO_AGE', 'CATEGORY_SPACED_180M']
    supersedes_plan_id TEXT REFERENCES article_publication_plans(plan_id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (plan_status IN ('PLANNED', 'SUPERSEDED', 'CANCELLED', 'BLOCKED')),
    CHECK (timezone = 'Asia/Jakarta')
);

-- Indices for performance and query optimization
CREATE INDEX IF NOT EXISTS idx_plans_article_status 
ON article_publication_plans(article_id, plan_status);

CREATE INDEX IF NOT EXISTS idx_plans_target_time 
ON article_publication_plans(target_publish_at, plan_status);

CREATE INDEX IF NOT EXISTS idx_plans_created_at 
ON article_publication_plans(created_at DESC);

-- Partial Unique Index: Exactly ONE active plan per article at any time
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_plan_per_article 
ON article_publication_plans(article_id) 
WHERE plan_status = 'PLANNED';


-- 2. Table: publication_planner_runs
-- Audit log of every execution of the Publication Planner
CREATE TABLE IF NOT EXISTS publication_planner_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id TEXT NOT NULL UNIQUE,                        -- E.g. 'prun_938472918'
    planner_profile TEXT NOT NULL,
    planner_version TEXT NOT NULL DEFAULT '1.0.0',
    target_date TEXT NOT NULL,                          -- 'YYYY-MM-DD'
    
    -- Inventory Metrics
    eligible_count INTEGER NOT NULL DEFAULT 0,
    planned_count INTEGER NOT NULL DEFAULT 0,
    deferred_count INTEGER NOT NULL DEFAULT 0,
    blocked_count INTEGER NOT NULL DEFAULT 0,
    effective_capacity INTEGER NOT NULL DEFAULT 0,
    
    -- Telemetry & Diagnostic Data
    signals_json TEXT NOT NULL DEFAULT '{}',            -- Telemetry multipliers used
    explanations_json TEXT NOT NULL DEFAULT '[]',       -- Decision log per candidate
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_planner_runs_date 
ON publication_planner_runs(target_date DESC, created_at DESC);


-- 3. Table: publication_plan_events
-- Immutable lifecycle events and audit trail for publication plans
CREATE TABLE IF NOT EXISTS publication_plan_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    plan_id TEXT NOT NULL REFERENCES article_publication_plans(plan_id) ON DELETE CASCADE,
    article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,                           -- 'CREATED' | 'SUPERSEDED' | 'RESCHEDULED' | 'PRIORITIZED' | 'CANCELLED' | 'BLOCKED'
    actor_type TEXT NOT NULL DEFAULT 'planner',         -- 'planner' | 'operator'
    actor_id TEXT NOT NULL,                             -- E.g. 'publication1-planner' or operator username
    details_json TEXT NOT NULL DEFAULT '{}',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (event_type IN ('CREATED', 'SUPERSEDED', 'RESCHEDULED', 'PRIORITIZED', 'CANCELLED', 'BLOCKED')),
    CHECK (actor_type IN ('planner', 'operator'))
);

CREATE INDEX IF NOT EXISTS idx_plan_events_plan 
ON publication_plan_events(plan_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_plan_events_article 
ON publication_plan_events(article_id, created_at DESC);
