name = "rancangloka"
main = "dist/_worker.js/index.js"
assets = { directory = "dist" }
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "rancangloka_db"
database_id = "3a86e9ad-410f-4440-884e-2eb813ec4cf7"

# Cloudflare R2 Object Storage Binding (for covers & media)
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "rancangloka-media"
