<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="id">
      <head>
        <title>XML Sitemap | RancangLoka SEO Engine</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style type="text/css">
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            background-color: #f8fafc;
            color: #1e293b;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            font-size: 13px;
            line-height: 1.5;
            padding: 40px 20px;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: #ffffff;
            border-radius: 16px;
            border: 1px solid #e2e8f0;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -2px rgba(0,0,0,0.05);
            overflow: hidden;
          }
          .header {
            padding: 30px;
            border-bottom: 1px solid #f1f5f9;
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            color: #ffffff;
          }
          .header h1 {
            font-size: 22px;
            font-weight: 800;
            letter-spacing: -0.02em;
            display: flex;
            align-items: center;
            gap: 10px;
          }
          .header p {
            color: #94a3b8;
            font-size: 13px;
            margin-top: 6px;
          }
          .stats-bar {
            background: #f8fafc;
            padding: 12px 30px;
            border-bottom: 1px solid #e2e8f0;
            display: flex;
            align-items: center;
            justify-content: space-between;
            font-size: 12px;
            font-weight: 600;
            color: #475569;
          }
          .stats-badge {
            background: #0071e3;
            color: white;
            padding: 3px 10px;
            border-radius: 20px;
            font-size: 11px;
            font-weight: 700;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            text-align: left;
          }
          th {
            background-color: #f8fafc;
            color: #64748b;
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            padding: 14px 30px;
            border-bottom: 1px solid #e2e8f0;
          }
          td {
            padding: 14px 30px;
            border-bottom: 1px solid #f1f5f9;
            color: #334155;
            font-size: 13px;
          }
          tr:hover td {
            background-color: #f8fafc;
          }
          a {
            color: #0071e3;
            text-decoration: none;
            font-weight: 500;
          }
          a:hover {
            text-decoration: underline;
          }
          .image-badge {
            display: inline-flex;
            align-items: center;
            gap: 4px;
            background: #ecfdf5;
            color: #059669;
            border: 1px solid #a7f3d0;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: 600;
          }
          .footer {
            padding: 20px 30px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
            border-top: 1px solid #f1f5f9;
            background: #ffffff;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1><span>🏡</span> RancangLoka XML Sitemap</h1>
            <p>Generated by RancangLoka Ultra-Fast Edge SEO Engine for Google, Bing, and Search Engine Indexers.</p>
          </div>

          <!-- Template for Sitemap Index -->
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <div class="stats-bar">
              <span>Sitemap Index / Daftar Sub-Sitemap</span>
              <span class="stats-badge"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> Sub-Sitemaps</span>
            </div>
            <table>
              <thead>
                <tr>
                  <th style="width: 70%;">Sitemap URL</th>
                  <th style="width: 30%;">Terakhir Diperbarui (Last Mod)</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <!-- Template for Standard URL Set -->
          <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <div class="stats-bar">
              <span>Daftar URL Terindeks</span>
              <span class="stats-badge"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs</span>
            </div>
            <table>
              <thead>
                <tr>
                  <th style="width: 55%;">Halaman URL</th>
                  <th style="width: 15%;">Gambar (Images)</th>
                  <th style="width: 30%;">Terakhir Diperbarui (Last Mod)</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td>
                      <xsl:choose>
                        <xsl:when test="count(image:image) &gt; 0">
                          <span class="image-badge">
                            🖼️ <xsl:value-of select="count(image:image)"/> Foto
                          </span>
                        </xsl:when>
                        <xsl:otherwise>
                          <span style="color: #94a3b8;">-</span>
                        </xsl:otherwise>
                      </xsl:choose>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <div class="footer">
            <p>© 2026 RancangLoka.com — Automated Rank Math Style Dynamic Edge Sitemap.</p>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
